typography_spectrum: 0.40223
color:
  brandColors:
    - '#ffffff'
    - '#3e1c1d'
    - '#a27d61'
    - '#cba98e'
    - '#e4d4bc'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d82c2237-a376-4562-84e4-18937e28f2d4.jpg
name: Wolf Measure
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: 1d8ddef3-9d4a-41ea-8463-25047114645c
    type: content
  - name: About
    id: 2c627043-7dc9-44dd-b039-550b27c17664
    type: content
  - name: Videos
    id: 807d3e96-992e-41ff-b27e-37df13c6148a
    type: content
  - name: Music
    id: 8398a040-73b9-4c5e-86ce-104681071a61
    type: content
favicon: null
title: Wolf Measure
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/321bc901-6e45-40ba-8d74-d7154147b48c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/321bc901-6e45-40ba-8d74-d7154147b48c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The official website for the band Wolf Measure.
purpose: []
