name: Wolf Measure
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e1c1d'
    - '#a27d61'
    - '#cba98e'
    - '#e4d4bc'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
