name: Wolf Measure
favicon: null
layout_spectrum: 0.59679
typography_spectrum: 0.40223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e1c1d'
    - '#a27d61'
    - '#cba98e'
    - '#e4d4bc'
  brandStrength: 0.8540502351243049
  lightness: 0.3007310947868973
  saturation: 0.2986290107946843
  rhythmicContrast: 0.6666477830149233
purpose: []
